import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
  en: {
    language: 'Language',
    user: 'User',
    post: 'Post',
    prodile: 'Profile',
    albums: 'Albums',
    account: 'Account',
    adderess: 'Address',
    compamy: 'Company',
    phone: 'Phone',
    userName: 'Username',
    email: 'Email',
    street: 'Street',
    suite: 'Suite',
    city: 'City',
    zipcode: 'Zipcode',
    companyName: 'Name',
    bs: 'Bs',
    catchPhrase: 'Catch phrase',
  },
  kz: {
    language: 'Тіл',
    user: 'Қолданушылар',
    post: 'Пост',
    prodile: 'Профиль',
    albums: 'Альбом',
    account: 'Аккаут',
    adderess: 'Мекенжай',
    compamy: 'Компания',
    phone: 'Телефон',
    userName: 'Пайдаланушы аты',
    email: 'Электронды пошта',
    street: 'Көше',
    suite: 'Люкс',
    city: 'Қала',
    zipcode: 'Пошта индексі',
    companyName: 'Компания аты',
    bs: 'БС',
    catchPhrase: 'Фразаны ұстау',
  },
  ru: {
    language: 'Язык',
    user: 'Пользователей',
    post: 'Пост',
    prodile: 'Профиль',
    albums: 'Альбом',
    account: 'Аккаунт',
    adderess: 'Адрес',
    compamy: 'Компания',
    phone: 'Телефон',
    userName: 'Имя пользователя',
    email: 'Электронная почта',
    street: 'Улица',
    suite: 'Люкс',
    city: 'Город',
    zipcode: ' Почтовый индекс',
    companyName: 'Имя компаний',
    bs: 'БС',
    catchPhrase: 'Поймать фразу',
  },
});
